--liquibase formatted sql


--changeset fleur:1
CREATE TABLE user_sessions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address    VARCHAR(255) NOT NULL,
    device_info   VARCHAR(255) NOT NULL,
    fingerprint   VARCHAR(255) NOT NULL,
    last_activity TIMESTAMPTZ  NOT NULL,
    is_active     BOOLEAN      NOT NULL,
    user_id       BIGINT REFERENCES users(id)
);

--rollback DROP TABLE user_sessions