--liquibase formatted sql


--changeset fleur:1
CREATE TABLE tokens
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL,
    expires_at      TIMESTAMPTZ  NOT NULL,
    is_revoked      BOOLEAN      NOT NULL,
    type            VARCHAR(32)  NOT NULL,
    user_session_id BIGINT REFERENCES user_sessions (id)
)

--rollback DROP TABLE tokens