--liquibase formatted sql


--changeset fleur:1
CREATE TABLE tokens
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token            VARCHAR(255) NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    is_revoked       BOOLEAN      NOT NULL,
    type             VARCHAR(30)  NOT NULL,
    user_session_id  BIGINT REFERENCES user_sessions (id),
    created_at       TIMESTAMPTZ  NOT NULL,
    last_modified_at TIMESTAMPTZ  NOT NULL
);

--rollback DROP TABLE tokens