--liquibase formatted sql


--changeset fleur:1
CREATE TABLE films
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR     NOT NULL,
    description      TEXT        NOT NULL,
    release_year     INT,
    duration         INT,
    age_rating       VARCHAR(30),
    trailer_url      VARCHAR,
    poster_url       VARCHAR,
    source_rating    DOUBLE PRECISION,
    status           VARCHAR(30),
    created_at       TIMESTAMPTZ NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL
);
--rollback DROP TABLE movies