--liquibase formatted sql


--changeset fleur:1
CREATE TABLE genres
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR     NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL
);
--rollback DROP TABLE genres