--liquibase formatted sql


--changeset fleur:1
CREATE TABLE actors
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR NOT NULL,
    born         DATE    NOT NULL,
    portrait_url VARCHAR,
    created_at       TIMESTAMPTZ NOT NULL,
    last_modified_at TIMESTAMPTZ NOT NULL
);

--rollback DROP TABLE actors