--liquibase formatted sql


--changeset fleur:1
CREATE TABLE film_persons
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id        BIGINT REFERENCES films (id)   NOT NULL,
    person_id      BIGINT REFERENCES persons (id) NOT NULL,
    film_role VARCHAR(50) NOT NULL,
    character_name VARCHAR
);
--rollback DROP TABLE actor_films