--liquibase formatted sql

--changeset fleur:1
CREATE TABLE user_lists
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT REFERENCES users (id) NOT NULL,
    film_id  BIGINT REFERENCES films (id) NOT NULL,
    type     VARCHAR(30)                  NOT NULL,
    added_at TIMESTAMPTZ                  NOT NULL

);
--rollback DROP TABLE user_lists