--liquibase formatted sql

--changeset fleur:1
CREATE TABLE collections
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR                      NOT NULL,
    description      VARCHAR,
    user_id          BIGINT REFERENCES users (id) NOT NULL,
    is_public        BOOLEAN                      NOT NULL,
    created_at       TIMESTAMPTZ                  NOT NULL,
    last_modified_at TIMESTAMPTZ                  NOT NULL
);
--rollback DROP TABLE film_collections
