--liquibase formatted sql


--changeset fleur:1
CREATE TABLE collection_items
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT REFERENCES collections (id) ON DELETE CASCADE NOT NULL,
    film_id  BIGINT REFERENCES films (id) ON DELETE CASCADE NOT NULL,
    added_at TIMESTAMPTZ                                    NOT NULL,
    position INT                                            NOT NULL
);
--rollback DROP TABLE film_collection_items