--liquibase formatted sql

--changeset fleur:1
CREATE TABLE ratings
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT REFERENCES users (id) NOT NULL,
    film_id          BIGINT REFERENCES films (id) NOT NULL,
    rating DOUBLE PRECISION NOT NULL,
    created_at       TIMESTAMPTZ                  NOT NULL,
    last_modified_at TIMESTAMPTZ                  NOT NULL
);
--rollback DROP TABLE ratings