--liquibase formatted sql

--changeset fleur:1
CREATE TABLE es_sync_dates
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_name     VARCHAR(32) NOT NULL,
    last_sync_time TIMESTAMPTZ NOT NULL
)
--rollback DROP TABLE es_sync_dates